DROP TABLE IF EXISTS ba.iterable_responses;
CREATE TABLE IF NOT EXISTS ba.iterable_responses AS
SELECT 
    a.campaign_id,
    a.campaign_name,
    a.message_medium,
    a.audience,
    a.email_type,
    a.launch_time,
    a.launch_hour,
    a.launch_date,
    a.launch_dow,
    a.launch_week,
    a.launch_month,
    a.template_id, 
    a.sms_template, 
    a.email_template_subject, 
    a.email_template_preheader,
    a.user_id,
    a.rendered_sms_message, 
    a.sms_send_count,
    a.ls_application_tag,
    a.ls_user_tag,
    a.previous_sms_send_cnt,
    a.previous_sms_send_cnt_14,
    a.previous_sms_send_cnt_30,
    a.previous_sms_send_cnt_90,
    a.previous_sms_send_cnt_180,
    a.previous_first_sms_send_date,
    a.previous_last_sms_send_date,
    a.previous_email_send_cnt,
    a.previous_email_send_cnt_14,
    a.previous_email_send_cnt_30,
    a.previous_email_send_cnt_90,
    a.previous_email_send_cnt_180,
    a.previous_first_email_send_date,
    a.previous_last_email_send_date,
    a.previous_sms_click_cnt,
    a.previous_sms_click_cnt_14,
    a.previous_sms_click_cnt_30,
    a.previous_sms_click_cnt_90,
    a.previous_sms_click_cnt_180,
    a.previous_first_sms_click_date,
    a.previous_last_sms_click_date,
    a.previous_email_click_cnt,
    a.previous_email_click_cnt_14,
    a.previous_email_click_cnt_30,
    a.previous_email_click_cnt_90,
    a.previous_email_click_cnt_180,
    a.previous_first_email_click_date,
    a.previous_last_email_click_date,
    a.previous_email_open_cnt,
    a.previous_email_open_cnt_14,
    a.previous_email_open_cnt_30,
    a.previous_email_open_cnt_90,
    a.previous_email_open_cnt_180,
    a.previous_first_email_open_date,
    a.previous_last_email_open_date,
    a.previous_application_date,
    a.previous_application_status,
    a.previous_assessment_status,
    a.previous_dispersal_date,
    a.previous_settled_date,
    a.previous_first_sms_send_interval,
    a.previous_last_sms_send_interval,
    a.previous_first_email_send_interval,
    a.previous_last_email_send_interval,
    a.previous_first_sms_click_interval,
    a.previous_last_sms_click_interval,
    a.previous_first_email_click_interval,
    a.previous_last_email_click_interval,
    a.previous_first_email_open_interval,
    a.previous_last_email_open_interval,
    a.previous_application_interval,
    a.previous_dispersal_interval,
    a.previous_settlement_interval,
    a.age,
    a.bounce_flag,
    a.open_flag,
    a.click_flag,
    a.unsubscribe_flag,
    a.complaint_flag,
    CASE WHEN app.application_id IS NOT NULL THEN 1 ELSE 0 END AS application_flag,
    CASE WHEN app.dispersal_date IS NOT NULL AND application_status='4.Funded' THEN 1 ELSE 0 END AS dispersal_flag,
    app.application_id,
    app.application_time,
    EXTRACT(HOUR FROM app.application_time) AS application_hour,
    DATE(app.application_date) AS application_date,
    app.application_week,
    app.application_month,
    DATE(app.dispersal_date) AS dispersal_date,
    app.dispersal_week,
    app.dispersal_month,
    DATEDIFF(DATE(app.application_date), a.launch_date) AS response_day,
    DATEDIFF(DATE(app.dispersal_date), a.launch_date) AS conversion_day,
    app.traffic_source,
    app.app_platform,
    app.app_start_type,
    app.app_side_completed,
    app.app_side_complete_type,
    app.completed_step,
    app.last_step,
    app.application_status,
    app.assessment_status,
    app.risk_level,
    app.finv_color_code,
    app.term_change_tag,
    app.reschedule_tag,
    app.attributed_utm,
    app.attributed_category,
    app.attributed_medium,
    app.attributed_campaign,
    app.total_amount as loan_amount,
    app.total_loan_amount,
    app.repayment_frequency,
    app.application_tag,
    app.user_tag,
    app.loan_tag,
    app.requested_loan_amount,
    app.requested_loan_tag,
    app.original_term_length,
    app.actual_term_length,
    app.original_term_avg,
    app.actual_term_avg,
    app.zip_code,
    app.suburb,
    app.state,
    app.family_type,
    app.dependents,
    app.total_income,
    app.total_expenses,
    app.gross_surplus,
    app.net_surplus,
    app.default_income,
    app.default_expenses,
    app.default_gross_surplus,
    app.approval_rules_decision,
    app.combined_ml_models_decision,
    app.is_auto_approved,
    app.is_bad_loan,
    app.approval_rules,
    app.combined_reasons,
    app.final_probability,
    app.base_probability,
    app.dpd_7_probability,
    app.dpd_14_probability,
    app.dpd_21_probability,
    app.dpd_28_probability,
    app.dpd_35_probability,
    app.dpd_42_probability,
    app.dpd_49_probability,
    app.LTI,
    app.PTI
FROM ba.iterable_targeting_history a
LEFT JOIN 
    (SELECT *, CAST(campaign_id AS BIGINT) AS campaign_id_numeric
    FROM
        (SELECT *,
             ROW_NUMBER() OVER(PARTITION BY user_id, campaign_id ORDER BY application_status DESC, application_time DESC) AS sep_no
        FROM 
            (SELECT *,
                 CASE WHEN LENGTH(attributed_campaign)=17 AND attributed_campaign rlike 'campaign_' THEN RIGHT(attributed_campaign,8)
                      ELSE LEFT(attributed_campaign,8) END AS campaign_id
            FROM ba.customer_profile_rawdata
            WHERE attributed_utm IN ('Iterable', 'sms', 'email')
            AND attributed_campaign IS NOT NULL AND attributed_campaign<>'Null'
            ) AS app
        WHERE campaign_id<>'campaign'
        ) AS app
    WHERE sep_no=1) AS app
ON a.user_id=app.user_id
AND a.campaign_id=app.campaign_id_numeric
ORDER BY a.launch_date, a.campaign_name, a.user_id
;